[package]
name = "generator-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]

[[bin]]
name = "generator"
path = "./bin/main.rs"

[[bin]]
name = "convert"
path = "./bin/convert.rs"

[dependencies]
vk-parse = "0.7"