pub const GOOGLE_HLSL_FUNCTIONALITY_1_SPEC_VERSION: u32 = 1;
pub const GOOGLE_HLSL_FUNCTIONALITY_1_EXTENSION_NAME: &std::ffi::CStr = crate::cstr!(
    "VK_GOOGLE_hlsl_functionality1"
);
pub const GOOGLE_HLSL_FUNCTIONALITY1_EXTENSION_NAME: &std::ffi::CStr = GOOGLE_HLSL_FUNCTIONALITY_1_EXTENSION_NAME;
